### ISSUE TITLE
xApp gets stuck a lot of times in new release

### ISSUE THREAD

**Issue by mas-oliveira** [srsran/oran-sc-ric#12]
Hello,

I don't know what's happening in this new release but sometimes when I run a monitoring KPM xApp I just get the API response:
```
{'response': 'OK', 'status': 200, 'payload': '{}', 'ctype': 'application/json', 'attachment': None, 'mode': 'plain'}
```

I don't know if this error is common to more users, but I'm now even using the simple_mon_xapp.py (python3 simple_mon_xapp.py --metrics=DRB.UEThpUl,DRB.RlcSduTransmittedVolumeDL) to make sure that wasn't one of my changes to cause this issue.

While I'm waiting for the E2 KPM messages I'm able to verify that the ping and iPerf commands still working and receiving normal logs without any apparent issue.

When I receive messages I'm able to check that this is the set granulPeriod:
-granulPeriod: 100

But I only receive messages every 10/20 seconds. I'm using 1 as slow down ratio and it doesn't like a lack of resources of my machine since I'm connecting only 3 UEs and transfering little amounts of data using iPerf.

Thanks a lot

**Comment by pgawlowicz** [comment]
so the issue is that the RIC indication messages are not received?

could you check if it works correctly if you change back the `rmr_flags=0x01` in `xAppBase.py`? check this commit https://github.com/srsran/oran-sc-ric/commit/16defc82c8eb4daa0d7093ec82b808e4673d1c1a

**Comment by mas-oliveira** [comment]
I changed but it's happening the same. It has a long delay until receive the first message and then I just get messages every 15/20s, there's any way to adjust this to get reports every 2s for instance?

**Comment by yc541** [comment]
I'm getting the similar behavior. Rerun the xApp sometimes solves it but it's pretty much 50/50 having the xApp working correctly. I tried changing the rmr_flags but the RAN wasn't happy decoding the control messages from the xApp.

**Comment by pgawlowicz** [comment]
indeed, this is what we observe. The KPM xApps work correctly with `rmr_flags=0x01`, but then RC xApps does not work. With `rmr_flags=0x00`, RC xApps can send a control request, but then KPM RIC indications are not always received. 

There might be some issue with RMR module.

**Comment by pgawlowicz** [comment]
Hi @mas-oliveira,
Could you test again with the newest version of this repository? probably you will need to remove and rebuild `python_xapp_runner` container and image.
