### ISSUE TITLE
Decoding Error in E2SM-KPM IndicationHeader at collectStartTime

### ISSUE THREAD

**Issue by LoganCome** [srsran/oran-sc-ric#14]
![Screenshot 2024-06-07 06_08_10](https://github.com/srsran/oran-sc-ric/assets/118045635/d05eb5be-95ff-4cc8-bf7f-554ab227d7f8)

We encountered an error during the RIC indication decoding process within our system, specifically tied to the E2SM-KPM-IndicationHeader-Format1.collectStartTime. The error message consistently points to "out of data (At bit offset: 8)," suggesting an issue with data integrity.

What could be causing this issue?

**Comment by pgawlowicz** [comment]
do you use the newest version of the srsRAN project?

**Comment by pgawlowicz** [comment]
no, i do not think so. Please try to remove all docker containers and images and build again.

**Comment by corbanvilla** [comment]
I am also seeing this error, on the latest build of oran-sc-ric and srsRAN... Any idea what may be causing it?

**Comment by pgawlowicz** [comment]
@LoganCome any update on this issue?

**Comment by pgawlowicz** [comment]
I am not able to reproduce the issue, please use the newest repositories and rebuild the docker images. Thanks!

**Comment by abida225** [comment]
i am running simple_rc_xapp that is sending min max prb. But in my ue i am not seeing any changes of prb. How can i verify that the control message of rc xapp changing the prb of ue?

**Comment by pgawlowicz** [comment]
@abida225 how do you check it?

**Comment by abida225** [comment]
Thats what i was asking. How do i check  that the prb is changing when xapp is sending rc message to the gnb?

**Comment by pgawlowicz** [comment]
You can sniff a e2ap messages with wireshark, or you can start iperf client to send data in DL to a UE. Then enablebl the console trace in gnb.

**Comment by abida225** [comment]
![Screenshot 2024-06-26 at 3 57 01 PM](https://github.com/srsran/oran-sc-ric/assets/126896416/3a626cf2-c20c-471f-bd0b-d5ffe1eb1840)
  Thank you for your response. How can i access the ric_dbaas?  Is there any documentation or command to view the logs or access the database?

**Comment by pgawlowicz** [comment]
You need to check the ORAN SC documents.
