### ISSUE TITLE
filed to connect srsran to e2

### ISSUE THREAD

**Issue by faratell** [srsran/oran-sc-ric#20]
Hello. 
I have installed srsran_project in a VM with local IP:192.168.75.151 and open5gs  in another VM 192.168.75.177
in a separate machine with local ip 192.168.75.143, I have installed near real-time ric from this repository.
I have replaced 10.0.2.10 with 192.168.75.143.
/oran-sc-ric$ grep -r "192.168.75.143"
docker-compose.yml:        ipv4_address: ${E2TERM_IP:-192.168.75.143}
ric/configs/routes.rtg:rte|1090|192.168.75.143:38000   # RIC_SCTP_CLEAR_ALL
ric/configs/routes.rtg:rte|1101|192.168.75.143:38000   # E2_TERM_KEEP_ALIVE_REQ
ric/configs/routes.rtg:rte|12002|192.168.75.143:38000  # RIC_E2_SETUP_RESP
ric/configs/routes.rtg:rte|12003|192.168.75.143:38000  # RIC_E2_SETUP_FAILURE
ric/configs/routes.rtg:rte|12010|192.168.75.143:38000  # RIC_SUB_REQ
ric/configs/routes.rtg:rte|12020|192.168.75.143:38000  # RIC_SUB_DEL_REQ
ric/configs/routes.rtg:rte|12040|192.168.75.143:38000  # RIC_CONTROL_REQ
ric/configs/e2term.conf:local-ip=192.168.75.143

and use this file as gnb.yaml config:
[gnb_zmq_e2.txt](https://github.com/user-attachments/files/15983629/gnb_zmq_e2.txt)
when i run docker compose up:
ic_submgr          | RMR is ready now ...
ric_rtmgr_sim       | 2024/06/26 06:49:30 DELETE /ric/v1/handles/e2t  body: {"E2TAddress":"192.168.75.143:38000"} elapsed: 35.47µs
ric_e2term          | {"ts":1719384664690,"crit":"ERROR","id":"E2Terminator","mdc":{"PID":"1","POD_NAME":"e2term_pod","CONTAINER_NAME":"ric_e2term","SERVICE_NAME":"ric_e2term_service","HOST_NAME":"ric_e2term_host","SYSTEM_NAME":"oran_sc_ric"},"msg":"GOT No messages from any xApp"}
ric_rtmgr_sim       | 2024/06/26 06:51:04 POST /ric/v1/handles/e2t  body: {"E2TAddress":"192.168.75.143:38000"} elapsed: 23.224µs
ric_rtmgr_sim       | 2024/06/26 06:51:10 DELETE /ric/v1/handles/e2t  body: {"E2TAddress":"192.168.75.143:38000"} elapsed: 32.117µs

But when i run gnb show this  error:

The PRACH detector will not meet the performance requirements with the configuration {Format 0, ZCZ 0, SCS 1.25kHz, Rx ports 1}.
Lower PHY in executor blocking mode.
N2: Connection to AMF on 192.168.75.177:38412 completed
Cell pci=1, bw=10 MHz, 1T1R, dl_arfcn=368500 (n3), dl_freq=1842.5 MHz, dl_ssb_arfcn=368410, ul_freq=1747.5 MHz

Connecting to NearRT-RIC on 192.168.75.143:36421
Failed to connect SCTP socket to 192.168.75.143:36421. error="Connection refused" timeout=0ms
srsRAN ERROR: Failed to create SCTP gateway.

How can solve it?

**Comment by pgawlowicz** [comment]
Hi, it is not an issue, but a different usage of the multi-container docker app. 

Changing the IP address of the E2Term container is not enough, as it is still connected to `ric_network` in the [docker-compose file](https://github.com/srsran/oran-sc-ric/blob/main/docker-compose.yml#L91-L93).

You probably need to connect the container also to the host network, but then the SCTP E2 service will be exposed over the host network, and internally the containers will communicate over the `ric_network`.

**Comment by faratell** [comment]
thanks.  But, how can connect the container to the host network?

**Comment by pgawlowicz** [comment]
read docker manual

**Comment by faratell** [comment]
Hello. I was installed  near RT RIC from bellow link and all pods are ok running:
https://gerrit.o-ran-sc.org/r/gitweb?p=ric-plt/ric-dep.git;a=blob;f=new-installer/README.md;h=a4cb085c12a61bfd7421c8b04aee147232688c42;hb=HEAD

kubectl get pods -n ricplt
NAME                                                                       READY    STATUS    RESTARTS       AGE
deployment-ricplt-a1mediator-7fdbb756c5-2qrx7     1/1     Running   1 (15h ago)   15h
deployment-ricplt-appmgr-6f445568d9-8xtpd           1/1     Running   0                  15h
deployment-ricplt-e2mgr-647999fcbc-zl755               1/1     Running   3 (15h ago)  15h
deployment-ricplt-e2term-alpha-5cdf68cb54-kcjlx     1/1     Running   0             15h
deployment-ricplt-rtmgr-86c96d6b6-mjwrv                1/1     Running   0             15h
deployment-ricplt-submgr-64c9b8cf89-kwd9h           1/1     Running   0             15h
ricplt-influxdb-0                                                            1/1     Running   0             15h
statefulset-ricplt-dbaas-server-0                                  1/1     Running   0             15h

Also i set my mcc and mnc in near RT RIC yaml file. ric ip an aux ip are also set as ip of my near RT RIC machine.


extsvcplt:
  ricip: "192.168.75.154"
  auxip: "192.168.75.154"
%%
e2mgr:
  e2mgr:
    image:
      registry: "nexus3.o-ran-sc.org:10002/o-ran-sc"
      name: ric-plt-e2mgr
      tag: 6.0.1
    privilegedmode: false
    globalRicId:
      ricId: "AACCE"
      mcc: "999"
      mnc: "70"
    rnibWriter:
      stateChangeMessageChannel: RAN_CONNECTION_STATUS_CHANGE
      ranManipulationMessageChannel: RAN_MANIPULATION
%%

i run open5gs and then gnb with e2 config as bellow :
e2:
  enable_du_e2: true                # Enable DU E2 agent (one for each DU insta>
  e2sm_kpm_enabled: true            # Enable KPM service module
  addr: 192.168.75.154                   # RIC IP address
  bind_addr: 192.168.75.151          # A local IP that the E2 agent binds to fo>
  port: 36422                       # RIC port

But have this error:
./gnb -c gnb_zmq_e2.yaml

--== srsRAN gNB (commit 40b17b429) ==--


The PRACH detector will not meet the performance requirements with the configuration {Format 0, ZCZ 0, SCS 1.25kHz, Rx ports 1}.
Lower PHY in executor blocking mode.
N2: Connection to AMF on 192.168.75.150:38412 completed
Cell pci=1, bw=10 MHz, 1T1R, dl_arfcn=368500 (n3), dl_freq=1842.5 MHz, dl_ssb_arfcn=368410, ul_freq=1747.5 MHz

Connecting to NearRT-RIC on 192.168.75.154:36422
Failed to connect SCTP socket to 192.168.75.154:36422. error="Connection refused" timeout=0ms
srsRAN ERROR: Failed to create SCTP gateway.

Can you help me how can solve it?

**Comment by pgawlowicz** [comment]
Hi @faratell, 
Unfortunately, I cannot help as I do not have experience with Kubernetes.

**Comment by abida225** [comment]
hi @faratell , did you able to connect dockerize osc-ric with gnb on two different vm?

**Comment by faratell** [comment]
Unfortunately not
