### ISSUE TITLE
Error while running simple_rc_xapp

### ISSUE THREAD

**Issue by pengnist** [srsran/oran-sc-ric#26]
Hi,

Still about the RC xApp. While trying to run it. the RIC reported errors. The kpm xApp would also fail. I am wondering if this is a known issue. Or any suggestions to debugging? 

Please find the RIC log when RC xApp started: 

```
Attaching to python_xapp_runner, ric_appmgr, ric_dbaas, ric_e2mgr, ric_e2term, ric_rtmgr_sim, ric_submgr
python_xapp_runner  | [?2004hroot@python_xapp_runner:/opt/xApps# 
ric_e2mgr           | {"ts":1721154943227,"crit":"INFO","id":"e2mgr","mdc":{"CONTAINER_NAME":"ric_e2mgr","HOST_NAME":"ric_e2mgr_host","PID":"1","POD_NAME":"e2mgr_pod","SERVICE_NAME":"ric_e2mgr_service","SYSTEM_NAME":"oran_sc_ric","e2mgr":"0.2.2","time":"2024-07-16T18:35:43Z"},"msg":"#app.main - Configuration {logging.logLevel: debug, http.port: 3800, rmr: { port: 3801, maxMsgSize: 65536}, routingManager.baseUrl: http://10.0.2.15:12020/ric/v1/handles/, notificationResponseBuffer: 100, bigRedButtonTimeoutSec: 5, maxRnibConnectionAttempts: 3, rnibRetryIntervalMs: 10, keepAliveResponseTimeoutMs: 4500, keepAliveDelayMs: 1500, e2tInstanceDeletionTimeoutMs: 15000,e2ResetTimeOutSec: 10,globalRicId: { ricId: AACCE, mcc: 001, mnc: 01}, rnibWriter: { stateChangeMessageChannel: RAN_CONNECTION_STATUS_CHANGE, ranManipulationChannel: RAN_MANIPULATION}"}
ric_e2mgr           | {"ts":1721154943227,"crit":"INFO","id":"e2mgr","mdc":{"CONTAINER_NAME":"ric_e2mgr","HOST_NAME":"ric_e2mgr_host","PID":"1","POD_NAME":"e2mgr_pod","SERVICE_NAME":"ric_e2mgr_service","SYSTEM_NAME":"oran_sc_ric","e2mgr":"0.2.2","time":"2024-07-16T18:35:43Z"},"msg":"Using config file: /opt/E2Manager/resources/configuration.yaml\n"}
ric_e2mgr           | dial tcp 10.0.2.12:6379: connect: connection refused
ric_appmgr          | dial tcp 10.0.2.12:6379: connect: connection refused
ric_dbaas           | 1:C 16 Jul 2024 18:35:43.586 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
ric_dbaas           | 1:C 16 Jul 2024 18:35:43.586 # Redis version=6.2.14, bits=64, commit=00000000, modified=0, pid=1, just started
ric_dbaas           | 1:C 16 Jul 2024 18:35:43.586 # Configuration loaded
ric_dbaas           | 1:M 16 Jul 2024 18:35:43.587 * monotonic clock: POSIX clock_gettime
ric_dbaas           | 1:M 16 Jul 2024 18:35:43.588 * Running mode=standalone, port=6379.
ric_dbaas           | 1:M 16 Jul 2024 18:35:43.588 # Server initialized
ric_dbaas           | 1:M 16 Jul 2024 18:35:43.589 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
ric_dbaas           | 1:M 16 Jul 2024 18:35:43.589 * Module 'exstrings' loaded from /usr/local/libexec/redismodule/libredismodule.so
ric_dbaas           | 1:M 16 Jul 2024 18:35:43.591 * Loading RDB produced by version 6.2.14
ric_dbaas           | 1:M 16 Jul 2024 18:35:43.591 * RDB age 33 seconds
ric_dbaas           | 1:M 16 Jul 2024 18:35:43.591 * RDB memory usage when created 0.83 Mb
ric_dbaas           | 1:M 16 Jul 2024 18:35:43.591 # Done loading RDB, keys loaded: 6, keys expired: 0.
ric_dbaas           | 1:M 16 Jul 2024 18:35:43.591 * DB loaded from disk: 0.000 seconds
ric_dbaas           | 1:M 16 Jul 2024 18:35:43.591 * Ready to accept connections
ric_e2term          | {"ts":1721154944973,"crit":"ERROR","id":"E2Terminator","mdc":{"PID":"1","POD_NAME":"e2term_pod","CONTAINER_NAME":"ric_e2term","SERVICE_NAME":"ric_e2term_service","HOST_NAME":"ric_e2term_host","SYSTEM_NAME":"oran_sc_ric"},"msg":"Error sending E2_TERM_INIT cause : RMR_ERR_NOENDPT - send//call could not find an endpoint based on msg type "}
ric_submgr          | {"ts":1721154947071,"crit":"INFO","id":"submgr","mdc":{"time":"2024-07-16T18:35:47"},"msg":"Using config file: /opt/config/submgr-config.yaml"}
ric_submgr          | redis: got 7 elements in COMMAND reply, wanted 6
ric_submgr          | redis: got 7 elements in COMMAND reply, wanted 6
ric_submgr          | redis: got 7 elements in COMMAND reply, wanted 6
ric_submgr          | redis: got 7 elements in COMMAND reply, wanted 6
ric_e2mgr exited with code 1
ric_e2term          | {"ts":1721154985978,"crit":"ERROR","id":"E2Terminator","mdc":{"PID":"139853295499008","POD_NAME":"e2term_pod","CONTAINER_NAME":"ric_e2term","SERVICE_NAME":"ric_e2term_service","HOST_NAME":"ric_e2term_host","SYSTEM_NAME":"oran_sc_ric"},"msg":"RMR failed: RMR_ERR_NOENDPT - send//call could not find an endpoint based on msg type. sending request 12001 to Xapp from gnbd_001_001_00019b_0"}
ric_e2term          | {"ts":1721155012763,"crit":"ERROR","id":"E2Terminator","mdc":{"PID":"139853295499008","POD_NAME":"e2term_pod","CONTAINER_NAME":"ric_e2term","SERVICE_NAME":"ric_e2term_service","HOST_NAME":"ric_e2term_host","SYSTEM_NAME":"oran_sc_ric"},"msg":"Failed to send message no CU entry gnb_001_001_00019b"}
ric_e2term          | {"ts":1721155012763,"crit":"ERROR","id":"E2Terminator","mdc":{"PID":"139853295499008","POD_NAME":"e2term_pod","CONTAINER_NAME":"ric_e2term","SERVICE_NAME":"ric_e2term_service","HOST_NAME":"ric_e2term_host","SYSTEM_NAME":"oran_sc_ric"},"msg":"Error handling Xapp message"}
ric_e2term          | {"ts":1721155017770,"crit":"ERROR","id":"E2Terminator","mdc":{"PID":"139853295499008","POD_NAME":"e2term_pod","CONTAINER_NAME":"ric_e2term","SERVICE_NAME":"ric_e2term_service","HOST_NAME":"ric_e2term_host","SYSTEM_NAME":"oran_sc_ric"},"msg":"Failed to send message no CU entry gnb_001_001_00019b"}
ric_e2term          | {"ts":1721155017770,"crit":"ERROR","id":"E2Terminator","mdc":{"PID":"139853295499008","POD_NAME":"e2term_pod","CONTAINER_NAME":"ric_e2term","SERVICE_NAME":"ric_e2term_service","HOST_NAME":"ric_e2term_host","SYSTEM_NAME":"oran_sc_ric"},"msg":"Error handling Xapp message"}
ric_e2term          | {"ts":1721155022778,"crit":"ERROR","id":"E2Terminator","mdc":{"PID":"139853295499008","POD_NAME":"e2term_pod","CONTAINER_NAME":"ric_e2term","SERVICE_NAME":"ric_e2term_service","HOST_NAME":"ric_e2term_host","SYSTEM_NAME":"oran_sc_ric"},"msg":"Failed to send message no CU entry gnb_001_001_00019b"}
ric_e2term          | {"ts":1721155022778,"crit":"ERROR","id":"E2Terminator","mdc":{"PID":"139853295499008","POD_NAME":"e2term_pod","CONTAINER_NAME":"ric_e2term","SERVICE_NAME":"ric_e2term_service","HOST_NAME":"ric_e2term_host","SYSTEM_NAME":"oran_sc_ric"},"msg":"Error handling Xapp message"}
ric_e2term          | {"ts":1721155027785,"crit":"ERROR","id":"E2Terminator","mdc":{"PID":"139853295499008","POD_NAME":"e2term_pod","CONTAINER_NAME":"ric_e2term","SERVICE_NAME":"ric_e2term_service","HOST_NAME":"ric_e2term_host","SYSTEM_NAME":"oran_sc_ric"},"msg":"Failed to send message no CU entry gnb_001_001_00019b"}
ric_e2term          | {"ts":1721155027785,"crit":"ERROR","id":"E2Terminator","mdc":{"PID":"139853295499008","POD_NAME":"e2term_pod","CONTAINER_NAME":"ric_e2term","SERVICE_NAME":"ric_e2term_service","HOST_NAME":"ric_e2term_host","SYSTEM_NAME":"oran_sc_ric"},"msg":"Error handling Xapp message"}
ric_e2term          | {"ts":1721155032791,"crit":"ERROR","id":"E2Terminator","mdc":{"PID":"139853295499008","POD_NAME":"e2term_pod","CONTAINER_NAME":"ric_e2term","SERVICE_NAME":"ric_e2term_service","HOST_NAME":"ric_e2term_host","SYSTEM_NAME":"oran_sc_ric"},"msg":"Failed to send message no CU entry gnb_001_001_00019b"}
ric_e2term          | {"ts":1721155032791,"crit":"ERROR","id":"E2Terminator","mdc":{"PID":"139853295499008","POD_NAME":"e2term_pod","CONTAINER_NAME":"ric_e2term","SERVICE_NAME":"ric_e2term_service","HOST_NAME":"ric_e2term_host","SYSTEM_NAME":"oran_sc_ric"},"msg":"Error handling Xapp message"}
ric_e2term          | {"ts":1721155037799,"crit":"ERROR","id":"E2Terminator","mdc":{"PID":"139853303891712","POD_NAME":"e2term_pod","CONTAINER_NAME":"ric_e2term","SERVICE_NAME":"ric_e2term_service","HOST_NAME":"ric_e2term_host","SYSTEM_NAME":"oran_sc_ric"},"msg":"Failed to send message no CU entry gnb_001_001_00019b"}
ric_e2term          | {"ts":1721155037799,"crit":"ERROR","id":"E2Terminator","mdc":{"PID":"139853303891712","POD_NAME":"e2term_pod","CONTAINER_NAME":"ric_e2term","SERVICE_NAME":"ric_e2term_service","HOST_NAME":"ric_e2term_host","SYSTEM_NAME":"oran_sc_ric"},"msg":"Error handling Xapp message"}
ric_e2term          | {"ts":1721155039226,"crit":"ERROR","id":"E2Terminator","mdc":{"PID":"139853295499008","POD_NAME":"e2term_pod","CONTAINER_NAME":"ric_e2term","SERVICE_NAME":"ric_e2term_service","HOST_NAME":"ric_e2term_host","SYSTEM_NAME":"oran_sc_ric"},"msg":"Message state RMR_ERR_NOENDPT - send//call could not find an endpoint based on msg type while sending request 1080 to Xapp from gnbd_001_001_00019b_0"}
ric_e2term          | {"ts":1721155039226,"crit":"ERROR","id":"E2Terminator","mdc":{"PID":"139853295499008","POD_NAME":"e2term_pod","CONTAINER_NAME":"ric_e2term","SERVICE_NAME":"ric_e2term_service","HOST_NAME":"ric_e2term_host","SYSTEM_NAME":"oran_sc_ric"},"msg":"SCTP_CONNECTION_FAIL message failed to send to xAPP"}

```

**Comment by pgawlowicz** [comment]
hi there was a change of e2 agent id.

In each app, you have to change the default if from `gnb_001_001_00019b` to `gnbd_001_001_00019b_0`

let me know if it helps, and i will merge this change.

**Comment by pengnist** [comment]
> hi there was a change of e2 agent id.
> 
> In each app, you have to change the default if from `gnb_001_001_00019b` to `gnbd_001_001_00019b_0`
> 
> let me know if it helps, and i will merge this change.

I tested kpm and rc xapps and can confirm it works! 
Thank you!

**Comment by newt2105** [comment]
Hi @pengnist , what version do you use (srsRAN_Project, oran-sc-ric, srsRAN _4G UE) to make the rc xapps work?
Thank you!

**Comment by pengnist** [comment]
> Hi [@pengnist](https://github.com/pengnist) , what version do you use (srsRAN_Project, oran-sc-ric, srsRAN _4G UE) to make the rc xapps work? Thank you!

Please check my answer in this thread: https://github.com/srsran/oran-sc-ric/issues/43#issuecomment-2715299274

**Comment by newt2105** [comment]
> > Hi [@pengnist](https://github.com/pengnist) , what version do you use (srsRAN_Project, oran-sc-ric, srsRAN _4G UE) to make the rc xapps work? Thank you!
> 
> Please check my answer in this thread: [#43 (comment)](https://github.com/srsran/oran-sc-ric/issues/43#issuecomment-2715299274)

Hi @pengnist, I've try your srsRAN version that you mentioned but when I run simple_rc_xapp.py , the DL doesn't change 
```
---------Signal-----------|-----------------DL-----------------|-----------UL-----------
rat  pci  rsrp   pl   cfo | mcs  snr  iter  brate  bler  ta_us | mcs   buff  brate  bler
 nr    1    40    0  -25u |  26   68   1.0    13k    0%    0.0 |  27     90   113k    0%
 nr    1    40    0  -27u |  26   67   1.1    13k    0%    0.0 |  27    0.0   113k    0%
 nr    1    41    0  -20u |  26  n/a   1.2    14k    0%    0.0 |  27    0.0   112k    0%
 nr    1    40    0  -26u |  26   68   1.2    15k    0%    0.0 |  27    0.0   112k    0%
 nr    1    40    0  -25u |  26   68   1.2    14k    0%    0.0 |  27    0.0   112k    0%
 nr    1    40    0  -18u |  26   68   1.2    14k    0%    0.0 |  27    0.0   114k    0%
 nr    1    40    0  -17u |  26  n/a   1.1    15k    0%    0.0 |  27    0.0   112k    0%
 nr    1    40    0  -22u |  26   66   1.1    13k    0%    0.0 |  27    0.0   112k    0%
 nr    1    40    0  -28u |  26  n/a   1.2    15k    0%    0.0 |  27    0.0   112k    0%
 nr    1    40    0  -19u |  26   66   1.2    14k    0%    0.0 |  27    0.0   112k    0%
 nr    1    40    0  -26u |  26   66   1.1    15k    0%    0.0 |  27    0.0   113k    0%

```  
Can you share your UE config or give me some advice?
Thanks!

**Comment by pengnist** [comment]
> > > Hi [@pengnist](https://github.com/pengnist) , what version do you use (srsRAN_Project, oran-sc-ric, srsRAN _4G UE) to make the rc xapps work? Thank you!
> > 
> > 
> > Please check my answer in this thread: [#43 (comment)](https://github.com/srsran/oran-sc-ric/issues/43#issuecomment-2715299274)
> 
> Hi [@pengnist](https://github.com/pengnist), I've try your srsRAN version that you mentioned but when I run simple_rc_xapp.py , the DL doesn't change
> 
> ```
> ---------Signal-----------|-----------------DL-----------------|-----------UL-----------
> rat  pci  rsrp   pl   cfo | mcs  snr  iter  brate  bler  ta_us | mcs   buff  brate  bler
>  nr    1    40    0  -25u |  26   68   1.0    13k    0%    0.0 |  27     90   113k    0%
>  nr    1    40    0  -27u |  26   67   1.1    13k    0%    0.0 |  27    0.0   113k    0%
>  nr    1    41    0  -20u |  26  n/a   1.2    14k    0%    0.0 |  27    0.0   112k    0%
>  nr    1    40    0  -26u |  26   68   1.2    15k    0%    0.0 |  27    0.0   112k    0%
>  nr    1    40    0  -25u |  26   68   1.2    14k    0%    0.0 |  27    0.0   112k    0%
>  nr    1    40    0  -18u |  26   68   1.2    14k    0%    0.0 |  27    0.0   114k    0%
>  nr    1    40    0  -17u |  26  n/a   1.1    15k    0%    0.0 |  27    0.0   112k    0%
>  nr    1    40    0  -22u |  26   66   1.1    13k    0%    0.0 |  27    0.0   112k    0%
>  nr    1    40    0  -28u |  26  n/a   1.2    15k    0%    0.0 |  27    0.0   112k    0%
>  nr    1    40    0  -19u |  26   66   1.2    14k    0%    0.0 |  27    0.0   112k    0%
>  nr    1    40    0  -26u |  26   66   1.1    15k    0%    0.0 |  27    0.0   113k    0%
> ```
> 
> Can you share your UE config or give me some advice? Thanks!

It looks to me your bitrate is a bit too low. Can you try increasing the bitrate and see if that changes?

**Comment by hnavidan** [comment]
> > Hi [@pengnist](https://github.com/pengnist) , what version do you use (srsRAN_Project, oran-sc-ric, srsRAN _4G UE) to make the rc xapps work? Thank you!
> 
> Please check my answer in this thread: [#43 (comment)](https://github.com/srsran/oran-sc-ric/issues/43#issuecomment-2715299274)

Hi @pengnist,
I tried the same version as yours and the RC works. However, the KPM crashes with metric style 5. Did you manage to get per-ue metrics in that version?

**Comment by pengnist** [comment]
> > > Hi [@pengnist](https://github.com/pengnist) , what version do you use (srsRAN_Project, oran-sc-ric, srsRAN _4G UE) to make the rc xapps work? Thank you!
> > 
> > 
> > Please check my answer in this thread: [#43 (comment)](https://github.com/srsran/oran-sc-ric/issues/43#issuecomment-2715299274)
> 
> Hi [@pengnist](https://github.com/pengnist), I tried the same version as yours and the RC works. However, the KPM crashes with metric style 5. Did you manage to get per-ue metrics in that version?

Yes, both KPM and RC worked with per-UE style in my deployment.

**Comment by hnavidan** [comment]
> > > > Hi [@pengnist](https://github.com/pengnist) , what version do you use (srsRAN_Project, oran-sc-ric, srsRAN _4G UE) to make the rc xapps work? Thank you!
> > > 
> > > 
> > > Please check my answer in this thread: [#43 (comment)](https://github.com/srsran/oran-sc-ric/issues/43#issuecomment-2715299274)
> > 
> > 
> > Hi [@pengnist](https://github.com/pengnist), I tried the same version as yours and the RC works. However, the KPM crashes with metric style 5. Did you manage to get per-ue metrics in that version?
> 
> Yes, both KPM and RC worked with per-UE style in my deployment.

Thanks for your quick reply!
Just to make sure, you used srsRAN_Project commit c4996c8ee4ca4264b4cb19e67d2f3d35ea0bd37a and oran-sc-ric commit dffe57fd3046303589139b942d3eb7689afa7611? 
Which kpm_report_style did work for you? My gNB crashes with style 5 and 2 and reports nothing on 3 and 4!
Did you apply any custom patch?

**Comment by pengnist** [comment]
> > > > > Hi [@pengnist](https://github.com/pengnist) , what version do you use (srsRAN_Project, oran-sc-ric, srsRAN _4G UE) to make the rc xapps work? Thank you!
> > > > 
> > > > 
> > > > Please check my answer in this thread: [#43 (comment)](https://github.com/srsran/oran-sc-ric/issues/43#issuecomment-2715299274)
> > > 
> > > 
> > > Hi [@pengnist](https://github.com/pengnist), I tried the same version as yours and the RC works. However, the KPM crashes with metric style 5. Did you manage to get per-ue metrics in that version?
> > 
> > 
> > Yes, both KPM and RC worked with per-UE style in my deployment.
> 
> Thanks for your quick reply! Just to make sure, you used srsRAN_Project commit c4996c8ee4ca4264b4cb19e67d2f3d35ea0bd37a and oran-sc-ric commit [dffe57f](https://github.com/srsran/oran-sc-ric/commit/dffe57fd3046303589139b942d3eb7689afa7611)? Which kpm_report_style did work for you? My gNB crashes with style 5 and 2 and reports nothing on 3 and 4! Did you apply any custom patch?

We used style 4 for per-UE KPM, and I don't remember we customized the provided reporting function but we added our own logic to the metrics. Their simple xapp worked when we tried it.

**Comment by hnavidan** [comment]
> > > > > > Hi [@pengnist](https://github.com/pengnist) , what version do you use (srsRAN_Project, oran-sc-ric, srsRAN _4G UE) to make the rc xapps work? Thank you!
> > > > > 
> > > > > 
> > > > > Please check my answer in this thread: [#43 (comment)](https://github.com/srsran/oran-sc-ric/issues/43#issuecomment-2715299274)
> > > > 
> > > > 
> > > > Hi [@pengnist](https://github.com/pengnist), I tried the same version as yours and the RC works. However, the KPM crashes with metric style 5. Did you manage to get per-ue metrics in that version?
> > > 
> > > 
> > > Yes, both KPM and RC worked with per-UE style in my deployment.
> > 
> > 
> > Thanks for your quick reply! Just to make sure, you used srsRAN_Project commit c4996c8ee4ca4264b4cb19e67d2f3d35ea0bd37a and oran-sc-ric commit [dffe57f](https://github.com/srsran/oran-sc-ric/commit/dffe57fd3046303589139b942d3eb7689afa7611)? Which kpm_report_style did work for you? My gNB crashes with style 5 and 2 and reports nothing on 3 and 4! Did you apply any custom patch?
> 
> We used style 4 for per-UE KPM, and I don't remember we customized the provided reporting function but we added our own logic to the metrics. Their simple xapp worked when we tried it.

Hmm, I see. For me something is wrong with the E2SM-KPM because it also doesn't report the UEThpDL and UEThpUL with report style 1 (it reports empty) and other report styles are not working!

**Comment by newt2105** [comment]
Hi, Is there any update on this issue?

**Comment by pgawlowicz** [comment]
The E2SM-RC PRB quota control was fixed in the newest srsRAN 5G Project release. Could you check?
Please also update the ORAN-SC-RIC repo.

Best,
Piotr
