### ISSUE TITLE
Inquire about how to send the control message from xAPP to gNB

### ISSUE THREAD

**Issue by lingyan98** [srsran/oran-sc-ric#27]
Now I have installed the project and I can run the xAPP example. However, how can I send a control message to gNB to change the setting of the gNB? Is there any provided function for sending control messages from xAPP to gNB?

**Comment by lingyan98** [comment]
> the only provided xApp that uses e2sm_rc module is this [one](https://github.com/srsran/oran-sc-ric/blob/main/xApps/python/simple_rc_xapp.py)
> 
> You can run it with:
> 
> ```
> docker compose exec python_xapp_runner ./simple_rc_xapp.py
> ```

Thanks for your replay, I have tested the simple_rc_xpp.py. But I got the following error in the 
`Connecting to NearRT-RIC on 10.0.2.10:36421
Available radio types: zmq.
==== gNB started ===
Type <h> to view help

Failure - RIC control not available in e2sm_kpm.
Failure - RIC control not available in e2sm_kpm.
Failure - RIC control not available in e2sm_kpm.
Failure - RIC control not available in e2sm_kpm.
Failure - RIC control not available in e2sm_kpm.
Failure - RIC control not available in e2sm_kpm.
Failure - RIC control not available in e2sm_kpm.
Failure - RIC control not available in e2sm_kpm.
Failure - RIC control not available in e2sm_kpm.
` 
How can I solve it ?

**Comment by lingyan98** [comment]
> the only provided xApp that uses e2sm_rc module is this [one](https://github.com/srsran/oran-sc-ric/blob/main/xApps/python/simple_rc_xapp.py)
> 
> You can run it with:
> 
> ```
> docker compose exec python_xapp_runner ./simple_rc_xapp.py
> ```

Thanks for your replay, I have tested this xAPP, but the gNB terminal didn't show anything, but the ric return the follow error
`ric_e2term          | {"ts":1721732580878,"crit":"ERROR","id":"E2Terminator","mdc":{"PID":"123457073305344","POD_NAME":"e2term_pod","CONTAINER_NAME":"ric_e2term","SERVICE_NAME":"ric_e2term_service","HOST_NAME":"ric_e2term_host","SYSTEM_NAME":"oran_sc_ric"},"msg":"Message state RMR_ERR_NOENDPT - send//call could not find an endpoint based on msg type while sending request 12041 to Xapp from gnbd_001_001_00019b_0"}
`

**Comment by pgawlowicz** [comment]
@lingyan98 any update on this issue? could you try with the newest version of both projects?

**Comment by lingyan98** [comment]
> @lingyan98 any update on this issue? could you try with the newest version of both projects?

Thank you for your reply. I have run this resource control successfully.
