### ISSUE TITLE
Question about using real USRP devices with the project

### ISSUE THREAD

**Issue by LoganCome** [srsran/oran-sc-ric#3]
- I noticed that the current setup uses ZMQ to emulate gNB. I was wondering if it's possible to use real USRP devices, such as the USRP B210, instead of the emulation.
- If the project does support real USRP devices, are there any specific configuration changes that need to be made to accommodate them?

**Comment by pgawlowicz** [comment]
The RIC part is independent of the deployment type (i.e, emulation over zmq or real wireless transmission using USRP). 
The provided tutorial is focused on ZMQ-based setup, as it makes it easy for everyone to replicate.

You can check our tutorial showing how to run the setup over a USRP [here](https://docs.srsran.com/projects/project/en/latest/tutorials/source/srsUE/source/index.html). Then you need to update gnb's config to enable E2 agent.

**Comment by s21sm** [comment]
It is possible with real USRP and with commercial UE. Here is my xapp output for real setup. I recommend using always the updated version. I am wondering how to control some parameter of gNB using xapp>>RIC agent.

![oran1(1)](https://github.com/srsran/oran-sc-ric/assets/20873147/7910a64d-9d07-4164-a111-1cd70348e258)

**Comment by pgawlowicz** [comment]
We will soon publish an example showing how to control gNB parameters using E2SM-RC module.

**Comment by s21sm** [comment]
@pgawlowicz Thanks.  In the Flexric, it is possible to access the saved database `[xApp]: DB filename = /tmp/xapp_db_1714648640282017 ` I am wondering if there is any such type of implementation in oran-sc-ric? database is very important for creating further decision making logic.

**Comment by pgawlowicz** [comment]
We are running a container with a database, check here: https://github.com/srsran/oran-sc-ric/blob/main/docker-compose.yml#L4
Also, if you sniff traffic on the RIC interface in Wireshark, you can see that some services are accessing it.

You will need to check the ORAN-SC-RIC resources on how to access it from your xapp.

**Comment by s21sm** [comment]
@pgawlowicz Could you please give some hints how to access / save the data in a database as it is in Flexric?

```
$ redis-cli -h 10.0.2.12 -p 6379
10.0.2.12:6379> keys *
1) "{e2Manager},GNB:00F110:0000000000000000000110011011"
2) "{e2Manager},GNB"
3) "{e2Manager},RAN:gnb_001_001_0000019b"
4) "{e2Manager},GENERAL"
5) "{e2Manager},E2TAddresses"
6) "{e2Manager},GNB:00F110:0000000000000110011011"
7) "{e2Manager},E2TInstance:10.0.2.10:38000"
8) "{e2Manager},RAN:gnb_001_001_00019b"
10.0.2.12:6379> 
```

**Comment by pgawlowicz** [comment]
Not sure if the python API for accessing the database is implemented in the Python xApp Framework (https://github.com/o-ran-sc/ric-plt-xapp-frame-py)
