### ISSUE TITLE
Error handling Xapp message

### ISSUE THREAD

**Issue by abida225** [srsran/oran-sc-ric#35]
I am running oran-sc-ric and gnb with (x310) and a cots ue. When i am running the rc xapp i am getting error on ric " Error handling Xapp message". In my zmq setup xapp works fine but when i moved to sdr based setup i am getting this error.
![Screenshot 2024-08-14 at 4 47 09 PM](https://github.com/user-attachments/assets/c6c5e539-dbcf-4c7c-970e-4fe9872b39e1)
[gnb_conf.txt](https://github.com/user-attachments/files/16618788/gnb_conf.txt)
[gnb (2).log](https://github.com/user-attachments/files/16618827/gnb.2.log)
xapp log 
![Screenshot 2024-08-14 at 5 01 06 PM](https://github.com/user-attachments/assets/631a1903-2b29-4b2e-92ec-91d1cd0ab1af)

how can i fix this issue?

**Comment by pgawlowicz** [comment]
you need to use the newest versions of both repos. As the e2 id used in the query is different than the one used by the e2 agent.

**Comment by abida225** [comment]
Thank you for you response. I have another question. If i want to run the ric and srsran project in a separate vm exactly which file and ip addresses do i need to modify?

**Comment by pgawlowicz** [comment]
check here: https://github.com/srsran/oran-sc-ric/discussions/34
