### ISSUE TITLE
xApp onboarding & deployment: error during RIC indication decoding: E2SM-KPM-IndicationHeader-Format1.colletStartTime: out of data (At bit offset: 8)

### ISSUE THREAD

**Issue by werefin** [srsran/oran-sc-ric#4]
Hi @pgawlowicz.
Firstly, thanks a lot for the great resources!
I was wondering about what the problem indicated below might be. I have meticulously  followed your procedure provided in the `README.md` however I am experiencing this problem when deploying the simple xApp. Do you know how to solve it? Do you have any suggestions regarding this error or any dependencies you can think of? 

`sudo docker compose exec python_xapp_runner ./simple_mon_xapp.py --metrics=DRB.UEThpDl,DRB.UEThpUl`

![Screenshot from 2024-04-22 17-49-04](https://github.com/srsran/oran-sc-ric/assets/48173952/6611b0cf-4f82-4268-94d3-bbbd932bb00c)

Thank you in advance.

**Comment by pgawlowicz** [comment]
Did you use the newest srsRAN-Project release or the `test` branch?

**Comment by werefin** [comment]
Hi, I'm using the srsRAN-Project release, I'll try with the `test` branch.

**Comment by werefin** [comment]
Hi, I'm sorry but I'm still experiencing some issues related to the xApp deployment, as you can see below. It seems that there's no E2 connection, but I followed the procedure as exposed in the documentation.

![Screenshot from 2024-04-24 10-56-52](https://github.com/srsran/oran-sc-ric/assets/48173952/24521a83-4454-4dae-bf74-dd7f20d50851)
![Screenshot from 2024-04-24 10-57-37](https://github.com/srsran/oran-sc-ric/assets/48173952/55da84d1-4806-4dbb-bddb-dc9942699cb4)

Do you know how to solve it?
Thanks in advance.

**Comment by pgawlowicz** [comment]
Hi, it seems that the gnb connected at `08:50:24` and disconnected at `08:50:47`, could you share your gnb logs?

**Comment by werefin** [comment]
Here it is the `gnb.log` file. 

[gnb.log](https://github.com/srsran/oran-sc-ric/files/15091843/gnb.log)

Thanks in advance.

**Comment by pgawlowicz** [comment]
and the gnb_e2.pcap?

**Comment by werefin** [comment]
I'm sorry, I thought it was attached, here it is:


[gnb_e2ap.pcap.log](https://github.com/srsran/oran-sc-ric/files/15091943/gnb_e2ap.pcap.log)

Thanks.

**Comment by pgawlowicz** [comment]
seems the RIC does not respond to the E2-Setup-Request from gnb. Could you show you routing table? `route -n`

**Comment by werefin** [comment]
![Screenshot from 2024-04-24 11-39-48](https://github.com/srsran/oran-sc-ric/assets/48173952/1538742c-91e7-47dc-ad54-6a9d2d8f43f3)

**Comment by werefin** [comment]
Hi, now it seems that it works correctly. Can you confirm my guess?

![Screenshot from 2024-04-24 12-07-45](https://github.com/srsran/oran-sc-ric/assets/48173952/aa9bf667-dfd4-4544-9f5f-eece876a30e5)

Where should I see the displayed messages?

**Comment by pgawlowicz** [comment]
yes, but you should also get indication messages and the xapp should display their content here

**Comment by werefin** [comment]
Yes, also restarting it I can't see any message displayed. Do you know where I could see those messages?

**Comment by pgawlowicz** [comment]
you can monitor e2ap traffic on the docker bridge interface with wireshark

**Comment by werefin** [comment]
Thank you so much. I'll close the issue, it was simply a problem related to the test branch.
