### ISSUE TITLE
The "simple_xapp.py" has no effect on the dl_throughput of the UE 

### ISSUE THREAD

**Issue by CCCodelover** [srsran/oran-sc-ric#43]
I'm experiencing the same problem as #21, is updating the srsRAN_Project version to srsRAN_Project-release_24_10 the only solution now? I would also like to ask if the ‘simple_xapp.py’ starts up and collects：
```
UE ID: 0, Max PRB Ratio: 100, Total TXed Data [MB]: 21.6
    21.6 MB of data transmitted to UE --> Switch Max PRB limit
    --->Send RIC Control Request to E2 node ID: gnbd_001_001_00019b_0 for UE ID: 0, PRB_min: 1, PRB_max: 10
```
What does Total TXed Data mean?

**Comment by CCCodelover** [comment]
[https://github.com/srsran/oran-sc-ric/blob/main/xApps/python/simple_xapp.py](https://github.com/srsran/oran-sc-ric/blob/main/xApps/python/simple_xapp.py )This is the simple_xapp.py I have enabled, the problem is that the gnb terminal doesn't change anything、

**Comment by CCCodelover** [comment]
The output of GNB looks like this:
`              |  15   1   28    29M  994    0   0%  1.08M |  65.5   ovl   27   199k  104    0   0%      0   0us  n/a
   1 4601 |  15   1   28    29M  993    0   0%  2.02M |  65.5   ovl   27   198k  107    0   0%     10   0us  n/a
   1 4601 |  15   1   28    29M  994    0   0%  3.22M |  65.5   ovl   27   195k  104    0   0%      0   0us  n/a
   1 4601 |  15   1   28    29M  994    0   0%  5.41M |  65.5   ovl   27   248k  101    0   0%      0   0us  n/a
   1 4601 |  15   1   28    29M  994    0   0%  6.12M |  65.5   ovl   27   216k  104    0   0%     10   0us  n/a
   1 4601 |  15   1   28    29M  993    0   0%  6.12M |  65.5   ovl   27   212k   99    0   0%      0   0us  n/a
   1 4601 |  15   1   28    29M  994    0   0%  6.13M |  65.5   ovl   27   227k  108    0   0%     10   0us  n/a
   1 4601 |  15   1   28    29M  994    0   0%  6.12M |  65.5   ovl   27   221k  103    0   0%     10   0us  n/a
   1 4601 |  15   1   28    29M  994    0   0%  6.12M |  65.5   ovl   27   199k  106    0   0%     10   0us  n/a

`Why doesn't 29M change

**Comment by pgawlowicz** [comment]
could you share your gnb logs?

**Comment by CCCodelover** [comment]
[gnb.log](https://github.com/user-attachments/files/17461665/gnb.log)
Please take a look for me.

**Comment by pgawlowicz** [comment]
you need to connect a UE, and start traffic, so that you can limit it with the xapp

**Comment by CCCodelover** [comment]
192.168.20.x is because I found that port e2 could not be opened when I was connecting to ric in gnb before, after changing all 10.0.2.x to 192.168.20.x, the connection was successfully established!

**Comment by CCCodelover** [comment]
Sorry, I'm recompiling the ric now and rebooting the whole set, maybe the gnb logs were overwritten by the previous error attempt. Can you tell me how #21 ended up being resolved. changing srsRAN_Project to srsRAN_Project-release_24_10?

**Comment by CCCodelover** [comment]
gnb should look similar to the one below:
`          |--------------------DL---------------------|-------------------------UL------------------------------
 pci rnti | cqi  ri  mcs  brate   ok  nok  (%)  dl_bs | pusch  rsrp  mcs  brate   ok  nok  (%)    bsr     ta  phr
   1 4601 |  15 1.0   28   6.8M  994    0   0%  6.15M |  65.5   ovl   27   233k   98    0   0%      0      0  n/a
   1 4601 |  15 1.0   28   6.8M  993    0   0%  6.15M |  65.5   ovl   27   246k  100    0   0%      0      0  n/a
   1 4601 |  15 1.0   28   6.8M  994    0   0%  6.15M |  65.5   ovl   27   231k  105    0   0%     10      0  n/a
   1 4601 |  15 1.0   28   6.8M  994    0   0%  6.15M |  65.5   ovl   27   245k   99    0   0%      0      0  n/a
   1 4601 |  15 1.0   28   6.8M  994    0   0%  6.15M |  65.5   ovl   27   231k  100    0   0%      0      0  n/a
   1 4601 |  15 1.0   28   6.8M  993    0   0%  6.15M |  65.5   ovl   27   227k  100    0   0%      0      0  n/a
   1 4601 |  15 1.0   28   6.8M  994    0   0%  6.15M |  65.5   ovl   27   238k   99    0   0%      0      0  n/a
   1 4601 |  15 1.0   28    22M  994    0   0%  6.12M |  65.5   ovl   27   235k  100    0   0%     10      0  n/a
   1 4601 |  15 1.0   28    29M  994    0   0%  6.12M |  65.5   ovl   27   229k   98    0   0%      0      0  n/a
   1 4601 |  15 1.0   28    29M  993    0   0%  6.12M |  65.5   ovl   27   230k   98    0   0%      0      0  n/a
   1 4601 |  15 1.0   28    29M  994    0   0%  6.12M |  65.4   ovl   27   227k  100    0   0%      0      0  n/a`
But my gnb was:
`1 4601 |  15 1.0   28    29M  994    0   0%  2.27M |  65.5   ovl   27   238k   95    0   0%      0      0  n/a
   1 4601 |  15 1.0   28    29M  994    0   0%  2.99M |  65.5   ovl   27   248k   99    0   0%      0      0  n/a
   1 4601 |  15 1.0   28    29M  994    0   0%  3.72M |  65.4   ovl   28   253k  100    0   0%      0      0  n/a
   1 4601 |  15 1.0   28    29M  993    0   0%   4.5M |  65.5   ovl   28   253k  100    0   0%      0      0  n/a
   1 4601 |  15 1.0   28    29M  994    0   0%  5.21M |  65.5   ovl   28   253k  100    0   0%      0      0  n/a
   1 4601 |  15 1.0   28    29M  994    0   0%  5.97M |  65.5   ovl   27   248k   99    0   0%      0      0  n/a
   1 4601 |  15 1.0   28    29M  994    0   0%  6.13M |  65.5   ovl   28   253k  100    0   0%      0      0  n/a
   1 4601 |  15 1.0   28    29M  993    0   0%  6.13M |  65.5   ovl   28   253k  100    0   0%      0      0  n/a
   1 4601 |  15 1.0   28    29M  994    0   0%  6.12M |  65.5   ovl   28   253k  100    0   0%      0      0  n/a
   1 4601 |  15 1.0   28    29M  994    0   0%  6.13M |  65.5   ovl   27   239k   96    0   0%      0      0  n/a
   1 4601 |  15 1.0   28    29M  994    0   0%  6.13M |  65.5   ovl   28   253k  100    0   0%      0      0  n/a
`
Here's my gnb log.
[Uploading gnb.log…]()

**Comment by CCCodelover** [comment]
[Uploading gnb.zip…]()

**Comment by CCCodelover** [comment]
[gnb.zip](https://github.com/user-attachments/files/17463051/gnb.zip)

**Comment by CCCodelover** [comment]
Dear Sir,
Thanks for your swift reply. The brate value stuck up with 29 M even when the xApp is running. I've tried a lot of things to fix it, and everything looks fine with the other components.
Best Regards@pgawlowicz

**Comment by pgawlowicz** [comment]
Please pull the newest code, and start the following xapp:
```
docker compose exec python_xapp_runner ./simple_rc_xapp.py
```

Start UDP iperf in DL, you should see the following gnb console trace:

```
---------Signal-----------|-----------------DL-----------------|-----------UL-----------
rat  pci  rsrp   pl   cfo | mcs  snr  iter  brate  bler  ta_us | mcs   buff  brate  bler
 nr    1     7    0 -4.8u |  27   69   1.1    29M    0%    0.0 |  27    3.0   256k    0%
 nr    1     7    0  4.4u |  27   69   1.1    29M    0%    0.0 |  27    0.0   241k    0%
 nr    1     7    0 -1.4u |  27   69   1.5    16M    0%    0.0 |  27    3.0   252k    0%
 nr    1     7    0 -2.7u |  27   69   1.8   3.3M    0%    0.0 |  27    3.0   227k    0%
 nr    1     7    0 -1.2u |  27   69   1.8   3.3M    0%    0.0 |  27    0.0   233k    0%
 nr    1     7    0 -3.8u |  27   69   1.8   3.3M    0%    0.0 |  27    3.0   230k    0%
 nr    1     7    0 -3.5u |  27   66   1.8   3.3M    0%    0.0 |  27    0.0   232k    0%
 nr    1     7    0 -2.6u |  27   69   1.4    16M    0%    0.0 |  27    0.0   255k    0%
 nr    1     7    0  576n |  27   69   1.1    29M    0%    0.0 |  27    3.0   249k    0%
 nr    1     7    0  480n |  27   69   1.1    29M    0%    0.0 |  27    0.0   258k    0%
```

**Comment by CCCodelover** [comment]
Dear Sir,
Thanks for your swift reply. The brate value stuck up with 29 M even when the xApp is running.

```~/oran-sc-ric$ docker compose exec python_xapp_runner ./simple_rc_xapp.py
```
RIC output is：
```
WARN[0000] /home/ubuntu/oran-sc-ric/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
1729647212397 7/RMR [INFO] ric message routing library on SI95 p=4560 mv=3 flg=00 id=a (f447e29 4.9.4 built: Dec 13 2023)
01:33:33 Send RIC Control Request to E2 node ID: gnbd_001_001_00019b_0 for UE ID: 0, PRB_min: 1, PRB_max: 5
Received RIC_CONTROL_ACK
01:33:38 Send RIC Control Request to E2 node ID: gnbd_001_001_00019b_0 for UE ID: 0, PRB_min: 1, PRB_max: 50
Received RIC_CONTROL_ACK
01:33:43 Send RIC Control Request to E2 node ID: gnbd_001_001_00019b_0 for UE ID: 0, PRB_min: 1, PRB_max: 5
Received RIC_CONTROL_ACK
01:33:48 Send RIC Control Request to E2 node ID: gnbd_001_001_00019b_0 for UE ID: 0, PRB_min: 1, PRB_max: 50
Received RIC_CONTROL_ACK
01:33:53 Send RIC Control Request to E2 node ID: gnbd_001_001_00019b_0 for UE ID: 0, PRB_min: 1, PRB_max: 5
Received RIC_CONTROL_ACK
^C01:33:58 Send RIC Control Request to E2 node ID: gnbd_001_001_00019b_0 for UE ID: 0, PRB_min: 1, PRB_max: 50

```
gnb output is：
```
       |--------------------DL---------------------|-------------------------UL------------------------------
 pci rnti | cqi  ri  mcs  brate   ok  nok  (%)  dl_bs | pusch  rsrp  mcs  brate   ok  nok  (%)    bsr     ta  phr
   1 4601 |  15 1.0   28    29M  994    0   0%  6.13M |  65.5   ovl   28   253k  100    0   0%     10      0  n/a
   1 4601 |  15 1.0   28    29M  994    0   0%  6.13M |  65.5   ovl   27   243k   97    0   0%      0      0  n/a
   1 4601 |  15 1.0   28    29M  993    0   0%  6.12M |  65.5   ovl   28   253k  100    0   0%      0      0  n/a
   1 4601 |  15 1.0   28    29M  994    0   0%  6.13M |  65.5   ovl   28   253k  100    0   0%      0      0  n/a
   1 4601 |  15 1.0   28    29M  994    0   0%  6.13M |  65.5   ovl   27   240k   98    0   0%      0      0  n/a
   1 4601 |  15 1.0   28    29M  994    0   0%  6.13M |  65.5   ovl   28   248k   98    0   0%      0      0  n/a
   1 4601 |  15 1.0   28    29M  993    0   0%  6.13M |  65.5   ovl   28   253k  100    0   0%      0      0  n/a
   1 4601 |  15 1.0   28    29M  994    0   0%  6.13M |  65.5   ovl   28   253k  100    0   0%      0      0  n/a
   1 4601 |  15 1.0   28    29M  994    0   0%  6.13M |  65.5   ovl   28   248k   98    0   0%      0      0  n/a
   1 4601 |  15 1.0   28    29M  994    0   0%  6.13M |  65.5   ovl   28   253k  100    0   0%      0      0  n/a
   1 4601 |  15 1.0   28    29M  993    0   0%  6.12M |  65.4   ovl   28   248k   98    0   0%      0      0  n/a

```

Best Regards @pgawlowicz

**Comment by pgawlowicz** [comment]
could you share your gnb logs?

**Comment by Keilwerth11270** [comment]
I am having similar issue. The simple xApp is able to influence PRB allocation and thus bitrate as shown in the srsRAN dashboard:
![grafana](https://github.com/user-attachments/assets/6d3e5deb-7e1e-4b14-9d9b-9f9127ced50f)

However the downlink throughput is not being influenced at all as can be seen from the KPM Monitoring xApp output in the [kpm_mon_xapp.log](https://github.com/user-attachments/files/17523720/kpm_mon_xapp.log). 

I have provided our gNB configuration: [gnb_conf.txt](https://github.com/user-attachments/files/17523784/gnb_conf.txt)

As well as the [simple_xapp.log](https://github.com/user-attachments/files/17523721/simple_xapp.log) (meaning the output it prints). The RIC acknowledge message is there but the change is also seen from the grafana image as well.

I am attaching the gNB logs. They are quite large as I did an iPerf session to generate downlink traffic and wanted to provide as much samples as possible.

[gnb_log_1.txt.zip](https://github.com/user-attachments/files/17523859/gnb_log_1.txt.zip)
[gnb_log_2.txt.zip](https://github.com/user-attachments/files/17523858/gnb_log_2.txt.zip)
[gnb_log_3.txt.zip](https://github.com/user-attachments/files/17523856/gnb_log_3.txt.zip)
[gnb_log_4.txt.zip](https://github.com/user-attachments/files/17523854/gnb_log_4.txt.zip)

I am using the previous release of srsRAN 24.04 on this machine, but I was facing similar issues with version 24.10, thank you for your time and support.

**Comment by pgawlowicz** [comment]
Please pull the newest srsRAN-Project release and try again. The version you are using (4ac5300d4) is from July.

**Comment by pgawlowicz** [comment]
@dnaudts: could you increase log level to debug and send new gnb logs?

**Comment by dnaudts** [comment]
> @dnaudts: could you increase log level to debug and send new gnb logs?

The way I solved it, was using a slightly older version (commit [e8ceafd]) and changing manually the RAN parameter ids: 10 -> 11, 11 ->12, 12 -> 13. Then it worked.

**Comment by pgawlowicz** [comment]
yes, we are aware of this issue, it will be fixed in the next project version.

**Comment by pengnist** [comment]
I am experiencing the same issue. The only srsrRAN Project that works with the dockerized osc ric RC xapp is commit c4996c8ee.

**Comment by pgawlowicz** [comment]
It will be fixed in the next code version.

**Comment by AlejandraOliver** [comment]
Hi @pengnist , what release of srsran Proyect are you using? Thanks!

**Comment by pengnist** [comment]
> Hi [@pengnist](https://github.com/pengnist) , what release of srsran Proyect are you using? Thanks!

I was using the srsran project commit c4996c8ee4ca4264b4cb19e67d2f3d35ea0bd37a. I haven't tried the latest version of oran-sc-ric with it yet. I was using oran-sc-ric commit dffe57fd3046303589139b942d3eb7689afa7611.

**Comment by AlejandraOliver** [comment]
Hi @pengnist , and simple_xapp.py of oran-sc-ric works fine for you?

**Comment by AlejandraOliver** [comment]
@pengnist @pengnist @pgawlowicz    have tried the release but when running simple_rc_xapp.py the traffic gets 0. Anyone knows how (which versions and gnb and ue config) I need to have in order to get this run correct?

Thanks in advanced!
