### ISSUE TITLE
Can’t start xAPP – chicken and egg problem (?)

### ISSUE THREAD

**Issue by lmendyk** [srsran/oran-sc-ric#49]
When starting ./simple_mon_xapp.py I get error:     
```
raise ApiException(http_resp=r)
ricxappframe.subsclient.rest.ApiException: (503)
Reason: Service Unavailable
```
Which I get from the submgr log is due to:
`"msg":"No E2 connection for ranName gnb_260_040_03e5d501"`
But there is no ran associated with E2Term due to (from e2term log):
`"msg":"GOT No messages from any xApp" `
But this from the e2term source code:
```
    //loop over term_init until first message from xApp
    handleTermInit(sctpParams);
```
Means that if there is no xAPP the E2TERM_INIT is send which results in e2mgr disassociates previously connected RAN which I can see in the logs:
`,"msg":"#E2TAssociationManager.DissociateRan - Dissociating RAN gnbd_260_040_0034d701_0 from E2T Instance address: 10.43.95.121:38000"}`

So it looks as “chicken and egg problem”
-	E2 Instance is disassociated with the RAN due to no xAPPs subscribed
-	xAPP subscription can not be made as RAN is disassicated with E2Term.

I don't know how to resolve that other than trying to hit the small "window of chance" when RAN is still associated with E2Term and mange to install xAPP before the loop in E2Term will disassociate the RAN due to know xAPs.  Practically I have not managed to have it running.

**Comment by pgawlowicz** [comment]
could you share gnb logs?

**Comment by lmendyk** [comment]
It is third-party RAN not the open source one, but I think it is not related to RAN but to this strange behavior of e2term which when no xAPPs sends  E2TERM_INIT and then e2mgr handling it by disassociating all RANs related to the e2Term instance.

So I was wondering how this xAPP runner from this project can work here.

**Comment by pgawlowicz** [comment]
Not sure, if I understand your problem. Could you elaborate more?

**Comment by pgawlowicz** [comment]
Did you follow the tutorial from the Readme of this repository?

**Comment by lmendyk** [comment]
Yes I did. I stared RIC, I started Core and RAN and I try starting (being in the container)
`./simple_mon_xapp.py --metrics=DRB.UEThpDl,DRB.UEThpUl --e2_node_id = <my gnodebeId taken from xterm logs>`

It complains no “Service Unavailable ” which refers to –e2_node_id ( I double checked first the id from the logs), but then realized that the gNodeb gets disassociated as … there is no xAPP -  from the observation, the E2Term_inti (and RAN disassociated) is done about every 2 minutes – so it is really hard to start xAPP before gNodeB gets  dissociated. 

I admit that I don’t understand the rationale behind the implemented logic.

**Comment by lmendyk** [comment]
I have managed to start the xAPP (I must be quick to start app before it is disassociated), but I get the following error from xAPP:
```
Subscribe to E2 node ID: gnbd_260_040_000e0001_0, RAN func: e2sm_kpm, Report Style: 1, metrics: ['DRB.UEThpDl', 'DRB.UEThpUl']
Successfully subscribed with Subscription ID:  2pnuLtrCfJ69NSiAWTbC1uqe7jE
Received Subscription ID to E2EventInstanceId mapping: 2pnuLtrCfJ69NSiAWTbC1uqe7jE -> 2
{'response': 'OK', 'status': 200, 'payload': '{}', 'ctype': 'application/json', 'attachment': None, 'mode': 'plain'}
10.42.2.240 - - [05/Dec/2024 15:55:07] "POST /ric/v1/subscriptions/response HTTP/1.1" 200 -
Error during RIC indication decoding: E2SM-KPM-IndicationHeader-Format1.colletStartTime: out of data (At bit offset: 8)
Error during RIC indication decoding: E2SM-KPM-IndicationHeader-Format1.colletStartTime: out of data (At bit offset: 8)
Error during RIC indication decoding: E2SM-KPM-IndicationHeader-Format1.colletStartTime: out of data (At bit offset: 8)
Error during RIC indication decoding: E2SM-KPM-IndicationHeader-Format1.colletStartTime: out of data (At bit offset: 8)
Error during RIC indication decoding: E2SM-KPM-IndicationHeader-Format1.colletStartTime: out of data (At bit offset: 8)
Error during RIC indication decoding: E2SM-KPM-IndicationHeader-Format1.colletStartTime: out of data (At bit offset: 8)
Error during RIC indication decoding: E2SM-KPM-IndicationHeader-Format1.colletStartTime: out of data (At bit offset: 8)
Error during RIC indication decoding: E2SM-KPM-IndicationHeader-Format1.colletStartTime: out of data (At bit offset: 8)
Error during RIC indication decoding: E2SM-KPM-IndicationHeader-Format1.colletStartTime: out of data (At bit offset: 8)
Error during RIC indication decoding: E2SM-KPM-IndicationHeader-Format1.colletStartTime: out of data (At bit offset: 8)
Error during RIC indication decoding: E2SM-KPM-IndicationHeader-Format1.colletStartTime: out of data (At bit offset: 8)
```
I'm using third party RAN, but may be you can advice what is the reason for that (specification incompatibility).  My gNodeB logs contain following messages: 

```
E2SM-KPM-IndicationMessage ::= {
indicationMessage-formats: E2SM-KPM-IndicationMessage-Format1 ::= {
measData: MeasurementData ::= {
MeasurementDataItem ::= {
measRecord: MeasurementRecord ::= {
0
0
}
}
}
measInfoList: MeasurementInfoList ::= {
MeasurementInfoItem ::= {
measType: DRB.UEThpDl
labelInfoList: LabelInfoList ::= {
LabelInfoItem ::= {
measLabel: MeasurementLabel ::= {
noLabel: 0 (true)
}
}
}
}
MeasurementInfoItem ::= {
measType: DRB.UEThpUl
labelInfoList: LabelInfoList ::= {
LabelInfoItem ::= {
measLabel: MeasurementLabel ::= {
noLabel: 0 (true)
}
}
}
}
}
}
}
E2SM-KPM-IndicationMessage ::= {
indicationMessage-formats: E2SM-KPM-IndicationMessage-Format1 ::= {
measData: MeasurementData ::= {
MeasurementDataItem ::= {
measRecord: MeasurementRecord ::= {
0
0
}
}
}
measInfoList: MeasurementInfoList ::= {
MeasurementInfoItem ::= {
measType: DRB.UEThpDl
labelInfoList: LabelInfoList ::= {
LabelInfoItem ::= {
measLabel: MeasurementLabel ::= {
noLabel: 0 (true)
}
}
}
}
MeasurementInfoItem ::= {
measType: DRB.UEThpUl
labelInfoList: LabelInfoList ::= {
LabelInfoItem ::= {
measLabel: MeasurementLabel ::= {
noLabel: 0 (true)
}
}
}
}
}
}
}

```

**Comment by pgawlowicz** [comment]
could you share gnb config file and logs?

**Comment by lmendyk** [comment]
Unfortunately I'm using third party RAN (commercial product) so the logs which I could I have provided in previous post.  I have seen som issues like this   #4  where the log log contained also the " E2SM-KPM-IndicationHeader-Format1.colletStartTime:" problem.   

I guess that it may be due to some incompatibility between RAN and RIC (in the issue the "test" RAN branch was mentioned ), so I was wondering If you could give some hints how can I resolve the issue (in my case changing rather the version of the RIC than RAN).  

My RAN claims to support: 
O-RAN.WG3.E2AP-v2.03
O-RAN.WG3.E2SM-v02.01
O-RAN.WG3.E2SM-KPM-v2.03

Franklyn speaking I couldn't find info about the versions supported by the RIC installed by this project instruction i-RELESE.

**Comment by pgawlowicz** [comment]
We use the following versions:
- O-RAN.WG3.E2AP-R003-v03.00
- O-RAN.WG3.E2SM-R003-v03.00
- O-RAN.WG3.E2SM-KPM-R003-v03.00
- O-RAN.WG3.E2SM-RC-R003-v03.00

Probably the biggest issue is with the timestamp size that was changed in the KPM asn1 definition (between the two versions):

```diff
- TimeStamp ::= OCTET STRING (SIZE(4))
+ TimeStamp ::= OCTET STRING (SIZE(8))
```

You might try to change the size to 4 in this [line](https://github.com/srsran/oran-sc-ric/blob/main/xApps/python/lib/asn1/e2sm-kpm-v4.00.asn#L32) in the `e2sm-kpm-v4.00.asn` file.

If this is not working, then you can try replacing this file with an older version. 
And do not forget to update the asn1 file name [here](https://github.com/srsran/oran-sc-ric/blob/main/xApps/python/lib/asn1/e2sm_kpm_packer.py#L8).

**Comment by lmendyk** [comment]
Thank you !.  I will try your hints, and provide the feedback once I have the results.

**Comment by lmendyk** [comment]
:)
```
RIC Indication Received from gnbd_260_040_000e0001_0 for Subscription ID: 6, KPM Report Style: 1
E2SM_KPM RIC Indication Content:
-ColletStartTime:  1900-01-01 00:00:00
-Measurements Data:
--Metric: DRB.UEThpDl, Value: [0]
--Metric: DRB.UEThpUl, Value: [214332]

RIC Indication Received from gnbd_260_040_000e0001_0 for Subscription ID: 6, KPM Report Style: 1
E2SM_KPM RIC Indication Content:
-ColletStartTime:  1900-01-01 00:00:00
-Measurements Data:
--Metric: DRB.UEThpDl, Value: [53626]
--Metric: DRB.UEThpUl, Value: [992]

RIC Indication Received from gnbd_260_040_000e0001_0 for Subscription ID: 6, KPM Report Style: 1
E2SM_KPM RIC Indication Content:
-ColletStartTime:  1900-01-01 00:00:00
-Measurements Data:
--Metric: DRB.UEThpDl, Value: [65588]
--Metric: DRB.UEThpUl, Value: [5818]

RIC Indication Received from gnbd_260_040_000e0001_0 for Subscription ID: 6, KPM Report Style: 1
E2SM_KPM RIC Indication Content:
-ColletStartTime:  1900-01-01 00:00:00
-Measurements Data:
--Metric: DRB.UEThpDl, Value: [158130]
--Metric: DRB.UEThpUl, Value: [13781]
```

@pgawlowicz - many thanks for help !
