### ISSUE TITLE
Route Manager Simulator: no initialization of RMR library

### ISSUE THREAD

**Issue by werefin** [srsran/oran-sc-ric#8]
Hi @pgawlowicz.

Sorry to bother you again. However, I noticed that regarding the route manager simulator, `rmr.init()` is not called to initialize the RMR library provided to send/receive messages via the xApp, as you can see below.

![image](https://github.com/srsran/oran-sc-ric/assets/48173952/24e6ecba-3d4e-4a79-b84f-5753a3c4d00c)

Obviously this I don't think can be done at the xApp level, but I should do it directly from the [`docker-compose.yml`](https://github.com/srsran/oran-sc-ric/blob/main/docker-compose.yml) file or  from the [`rtmng.yaml`](https://github.com/srsran/oran-sc-ric/blob/main/ric/configs/rtmgr.yaml). 

Do you have any ideas on how to solve this issue? Would it be possible to start the RMR library for the route manager somehow from the docker files?

Thanks in advance.

Best regards,
David

**Comment by pgawlowicz** [comment]
Do you know how to start it manually inside docker?
Then, you can just add a `RUN` command here: https://github.com/srsran/oran-sc-ric/blob/main/ric/images/rtmgr_sim/Dockerfile

**Comment by werefin** [comment]
Hi @pgawlowicz, thanks for the answer.

Should I follow something like [this](https://github.com/o-ran-sc/ric-plt-rtmgr/blob/master/Dockerfile)? In which the `rmr` package is first taken from `packagecloud.io` and then run it?

Thanks in advance.

**Comment by pgawlowicz** [comment]
wait, do you want RMR in Routing Manager Simulator or do you want to use the real Routing Manager?

**Comment by pgawlowicz** [comment]
no problem, but why do you need RMR in the simulator?

**Comment by pgawlowicz** [comment]
I think you need L8-L13, L31,L33, L34, L60 from: 
https://github.com/srsran/oran-sc-ric/blob/main/ric/images/ric-plt-xapp-frame-py/Dockerfile

**Comment by werefin** [comment]
> no problem, but why do you need RMR in the simulator?

The main reason is that I want to retrieve first the routing table using RMR library, and after that manipulate it to perform some tests.

> I think you need L8-L13, L31,L33, L34, L60 from: https://github.com/srsran/oran-sc-ric/blob/main/ric/images/ric-plt-xapp-frame-py/Dockerfile

That seems that it is not activated properly, since there's no `RMR [info]` message displayed.

**Comment by pgawlowicz** [comment]
could you enter the docker container and try to run `/opt/e2/rmr_probe` ?

**Comment by werefin** [comment]
That's the result:

![image](https://github.com/srsran/oran-sc-ric/assets/48173952/24bd3a6b-80d1-4146-bb26-49bbe12ae3eb)

**Comment by pgawlowicz** [comment]
Did you copy the lines listed above and rebuild the docker image?
could you check if there is `rmr_probe` inside this container?

**Comment by pgawlowicz** [comment]
hmm, the each docker container in this repo uses this route table https://github.com/srsran/oran-sc-ric/blob/main/ric/configs/routes.rtg, so you do not have to get it thought the RMR. Since this file is linked to each container it is enough to manipulate this file on your local machine as you initially tested. Or do you want to do sth more?
